### ISSUE TITLE
如何避免在所有的应用中共享输入状态？

### ISSUE THREAD

**Issue by FengZhongShaoNian** [fcitx/fcitx5-rime#101]
在 fcitx5 的配置面板中设置了不共享输入状态，但是在 rime 里每个窗口的输入状态都是共享的。
![image](https://github.com/fcitx/fcitx5-rime/assets/16934087/f1a6fd0d-1f67-48bf-9a33-6e0b4865d42d)

问题如下面的视频所示:（视频大小5.5M）

https://github.com/fcitx/fcitx5-rime/assets/16934087/1f414c0b-1072-4724-a587-2f9b227dafad

另外，“在特定程序里关闭中文输入”的这个功能也没有生效。我的`~/.local/share/fcitx5/rime/fcitx5.custom.yaml`文件的内容如下：
```yaml
patch:
  # 通知栏显示方式以及 ascii_mode 应用，与外观无关
  show_notifications_via_notification_center: true
  # 以下软件默认英文模式
  "app_options/scrcpy":
    ascii_mode: true
  "app_options/konsole":
    ascii_mode: true
  "app_options/blackbox":
    ascii_mode: true
  "app_options/gnome-terminal-server":
    ascii_mode: true
  "app_options/gnome-terminal":
    ascii_mode: true
  "app_options/java":
    ascii_mode: true
  "app_options/com.vixalien.sticky":
    ascii_mode: true
  "app_options/rustdesk":
    ascii_mode: true
  "app_options/krunner":
    ascii_mode: true
  "app_options/utools":
    ascii_mode: true
  "app_options/plasmashell":
    ascii_mode: true
  "app_options/latte-dock":
    ascii_mode: true
  "app_options/dolphin":
    ascii_mode: true
  "app_options/kate":
    ascii_mode: true
  "app_options/java_for_idea":
    ascii_mode: true
  "app_options/java_for_clion":
    ascii_mode: true
  "app_options/java_for_datagrip":
    ascii_mode: true
  "app_options/navicat":
    ascii_mode: true
  "app_options/sunloginclient":
    ascii_mode: true
  "app_options/another-redis-desktop-manager":
    ascii_mode: true
```

另外，我的系统信息如下：
```
# System Details Report
---

## Report details
- **Date generated:**                              2024-05-05 16:19:07

## Software Information:
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.9-arch1-1
```
