### ISSUE TITLE
switch_key commit_code not working

### ISSUE THREAD

**Issue by zzhixin** [fcitx/fcitx5-rime#137]
I followed spirit of this [guide](https://github.com/rime/home/wiki/CustomizationGuide#%E8%A8%AD%E5%AE%9A%E9%A0%85%E9%80%9F%E6%9F%A5%E6%89%8B%E5%86%8A) to customize my fcitx5-rime. All my modification of rime is
1. `vim ~/.local/share/fcitx5/rime/default.custom.yaml`
2. Enter following into the new `default.custom.yaml` file. Obviously, just try (1) to disable `Control+grave` hotkeys; (2) to set luna_pinyin_simp; (3) to set Shift_L as commit_code.
```
patch:
  schema_list:
    - schema: luna_pinyin_simp
  
  switcher:
    caption: 〔方案選單〕
    hotkeys:
      - Control+Shift+grave
      - F4

  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Shift_L: commit_code
      Shift_R: commit_text
      Control_L: noop
      Control_R: noop
      Caps_Lock: clear
      Eisu_toggle: clear
```
3. click deploy button of the fcitx5 config tray.

And my intention (1) and (2) are completed, but (3) fails. Type left shiift in the middle of chinese input leads to chinese text commited not english chars.

Although I understand that it is not recommanded to modify the files in `/usr/share/rime-data`, I tried to modify the default.yaml file in it and still not effective.

Where am I wrong?
