### ISSUE TITLE
[Bug] 关于Rime的 alternative_select_keys 和 alternative_select_labels

### ISSUE THREAD

**Issue by hosxy** [fcitx/fcitx5-rime#3]
fcitx5-rime 不能使用 alternative_select_keys 和 alternative_select_labels,

如果在 default.custom.yaml 中使用 alternative_select_keys 会直接乱码(更像是缺字体的那种)，eg:
```
patch:
  menu:
    page_size: 7
    alternative_select_keys: "ABCDEFGHIJ"
```
![深度截图_选择区域_20191227143351](https://user-images.githubusercontent.com/17108640/71505008-8a705d00-28b6-11ea-9921-8cea5ff8f0b0.png)

而 alternative_select_labels 没有任何效果
```
patch:
  menu:
    page_size: 7
    alternative_select_labels: [甲, 乙, 丙, 丁, 戊, 己, 庚, 辛, 壬, 癸]
```
![深度截图_选择区域_20191227144252](https://user-images.githubusercontent.com/17108640/71505154-2d28db80-28b7-11ea-86de-6b8f86a91c50.png)

Rime 那里找到两个 pr和issue
https://github.com/rime/librime/pull/58
https://github.com/rime/librime/issues/57

这个在 windows下的 weasel 和 ibus-rime 都是可以用的，下面是 ibus-rime的截图：

![深度截图_选择区域_20191227145503](https://user-images.githubusercontent.com/17108640/71505977-2485d480-28ba-11ea-9046-aac87f735f45.png)
