### ISSUE TITLE
“针对特定程序默认启用中/英文状态”的功能已实现，但对urxvt和java程序尚未生效

### ISSUE THREAD

**Issue by tankb52** [fcitx/fcitx5-rime#41]
基于此 issue [fcitx5-rime/issues/40](https://github.com/fcitx/fcitx5-rime/issues/40) 产生的新问题。
系统： Debian GNU/Linux bookworm/sid
Fcitx5: 5.0.13

在 `~/.local/share/fcitx5/rime/fcitx5.custom.yaml `写入的规则如下
```
patch:
  "app_options/nvim-qt":
    ascii_mode: true
  "app_options/vim":
    ascii_mode: true
  "app_options/gvim":
    ascii_mode: true
  "app_options/freeplane":
    ascii_mode: true
  "app_options/java":
    ascii_mode: false
  "app_options/urxvt":
    ascii_mode: true
  "app_options/rxvt":
    ascii_mode: true
  "app_options/URxvt":
    ascii_mode: true
  "app_options/Rxvt":
    ascii_mode: true
  "app_options/xterm":
    ascii_mode: true
  "app_options/alacritty":
    ascii_mode: true
  "app_options/scrcpy":
    ascii_mode: true
  "app_options/geany":
    ascii_mode: true
  "app_options/zim":
    ascii_mode: true
```

其他程序中都已经实现了默认英文效果，但在 `rxvt/urxvt` 这个终端程序没有生效，目前是将输入法的默认状态改成英文来使用的。

是不是这个方法 `dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo` 取的名字不对？

另外对于用 java 编写的思维导图软件 `freeplane` ，获取到的名字是 `java` ，也能生效。但这个名字岂不是要针对所有的java 程序都启用了？
