### ISSUE TITLE
对快捷键打补丁，Shift键无效

### ISSUE THREAD

**Issue by pzzxqj** [fcitx/fcitx5-rime#52]
在`switcher/hotkeys`和`key_binder/bindings`中添加快捷键，Shift修饰的快捷键无效。但是默认生成的`key_binder`中带用Shift快捷键是有效的。

另附一个同样问题https://github.com/rime/home/issues/1175#issue-1460068036

**Comment by wengxt** [comment]
请提供你的配置以供测试

**Comment by pzzxqj** [comment]
我发现了解决方法，https://github.com/rime/home/issues/1175#issuecomment-1454704673
```yaml
#default.custom.yaml
patch:
  switcher/hotkeys:
    - "Control+Shift+grave" # 这个无效
    - "Control+Shift+asciitilde" # 这个可以
```
