### ISSUE TITLE
ascii_composer/switch_key 里面的Control_L会调用Caps_Lock的问题

### ISSUE THREAD

**Issue by c02y** [fcitx/fcitx5-rime#60]
我在系统级禁用掉了Caps_Lock按键，所以不管有没有输入框，按Caps_Lock都不会切换到大写

但是发现在只要设置Control_L切换中英文，文本输入框内Caps_Lock也可以切换中英文，禁用Control_L也会禁用Caps_Lock

把Control_L设置成任何值(clear, noop, commit_code, commit_text, inline_ascii)，Caps_Lock效果会变成Control_L效果一样，不管设置里面Caps_Lock设置成什么值

文件default.yaml:
```
ascii_composer:
  good_old_caps_lock: true  # true | false
  switch_key:
    Caps_Lock: clear      # commit_code | commit_text | clear
    Shift_L: noop  # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: noop         # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: commit_code       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop

```

FYI:
rime config: [rime-ice](https://github.com/iDvel/rime-ice/) or [rime-config](https://github.com/expoli/rime-config/)
Arch Linux
fcitx5-rime
default.yaml: 只使用小鹤双拼
```
  schema_list:
    - schema: double_pinyin_flypy
```

似乎不是rime配置的问题，所以我在fcitx5-rime和librime都提交了这个issue
